# Generated by Django 2.1.4 on 2018-12-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('idd', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=9)),
                ('request', models.CharField(max_length=200)),
                ('nppl', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=200)),
                ('offer', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('dest', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200)),
                ('agency', models.CharField(max_length=200)),
            ],
        ),
    ]
